/*
# Create trips table for AI Travel Planner

1. New Tables
- `trips`
  - `id` (uuid, primary key)
  - `destination` (text, not null) — the city/destination the user wants to visit
  - `budget` (integer, not null) — approximate travel budget in USD
  - `days` (integer, not null) — number of days for the trip
  - `preferences` (text[], default empty) — array of preference tags (adventure, nature, food, shopping, culture, relaxation, family)
  - `travel_style` (text, default 'balanced') — budget, balanced, or luxury
  - `itinerary` (jsonb, not null) — the full day-by-day itinerary generated by the planner
  - `summary` (text) — short AI-generated summary of the trip
  - `estimated_total_cost` (integer) — estimated total cost of the trip
  - `cover_image` (text) — URL of a cover image for the trip
  - `created_at` (timestamptz, default now)
  - `updated_at` (timestamptz, default now)

2. Security
- Enable RLS on `trips`.
- Allow anon + authenticated full CRUD because this is a single-tenant app with no sign-in screen.
- All data is intentionally shared/public across the app instance.

3. Indexes
- Index on `created_at` for sorting trips by most recent.
*/

CREATE TABLE IF NOT EXISTS trips (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  destination text NOT NULL,
  budget integer NOT NULL,
  days integer NOT NULL,
  preferences text[] DEFAULT '{}',
  travel_style text DEFAULT 'balanced',
  itinerary jsonb NOT NULL,
  summary text,
  estimated_total_cost integer,
  cover_image text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE trips ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_trips" ON trips;
CREATE POLICY "anon_select_trips" ON trips FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_trips" ON trips;
CREATE POLICY "anon_insert_trips" ON trips FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_trips" ON trips;
CREATE POLICY "anon_update_trips" ON trips FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_trips" ON trips;
CREATE POLICY "anon_delete_trips" ON trips FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_trips_created_at ON trips (created_at DESC);
